all:
  hosts:
    inetRouter:
      ansible_host: 192.168.17.1
      ansible_port: 20022
      ansible_user: vagrant
      ansible_password: vagrant
    centralRouter:
      ansible_host: 192.168.17.1
      ansible_port: 21022
      ansible_user: vagrant
      ansible_password: vagrant
    Office1Router:
      ansible_host: 192.168.17.1
      ansible_port: 22022
      ansible_user: vagrant
      ansible_password: vagrant
    testServer1:
      ansible_host: 192.168.17.1
      ansible_port: 23022
      ansible_user: vagrant
      ansible_password: vagrant
    testClient1:
      ansible_host: 192.168.17.1
      ansible_port: 24022
      ansible_user: vagrant
      ansible_password: vagrant
    testServer2:
      ansible_host: 192.168.17.1
      ansible_port: 25022
      ansible_user: vagrant
      ansible_password: vagrant
    testClient2:
      ansible_host: 192.168.17.1
      ansible_port: 26022
      ansible_user: vagrant
      ansible_password: vagrant

