all:
  hosts:
    inetRouter:
      ansible_host: 127.0.0.1
      ansible_port: 20022
      ansible_private_key_file: .vagrant/machines/inetRouter/virtualbox/private_key
    centralRouter:
      ansible_host: 127.0.0.1
      ansible_port: 21022
      ansible_private_key_file: .vagrant/machines/centralRouter/virtualbox/private_key
    Office1Router:
      ansible_host: 127.0.0.1
      ansible_port: 22022
      ansible_private_key_file: .vagrant/machines/Office1Router/virtualbox/private_key
    testServer1:
      ansible_host: 127.0.0.1
      ansible_port: 23022
      ansible_private_key_file: .vagrant/machines/testServer1/virtualbox/private_key
    testClient1:
      ansible_host: 127.0.0.1
      ansible_port: 24022
      ansible_private_key_file: .vagrant/machines/testClient1/virtualbox/private_key
    testServer2:
      ansible_host: 127.0.0.1
      ansible_port: 25022
      ansible_private_key_file: .vagrant/machines/testServer2/virtualbox/private_key
    testClient2:
      ansible_host: 127.0.0.1
      ansible_port: 26022
      ansible_private_key_file: .vagrant/machines/testClient2/virtualbox/private_key

